### ISSUE TITLE
Timeout for DockerReadyWaitCondition to short

### ISSUE THREAD

**Issue by jagin** [apls777/spotty#24]
Hi @apls777 

I think that 10 minutes for building a docker image is sometimes to short. Installing miniconda with some additional packages for pytorch task is a little bit longer and `spotty start` failed. In the CloudFormation stack i got the following error 'Failed to receive 1 resource signal(s) within the specified duration' but after a few minutes more the docker image is up and running.

Regards

Jarek

**Comment by apls777** [comment]
Hi @jagin,

Oh, you're right, 10 minutes it's too short. I will change it to 30 minutes with the next release. But for now you still should be able to connect to the instance with the `spotty ssh` command, even if the stack is failed.

Thanks!

**Comment by apls777** [comment]
It's not related to the issue, just a suggestion: if, as you said, you want to share this project with other people, consider pushing your image to the [Docker Hub](https://hub.docker.com/). Then you can just specify the image name in the configuration file. It will save other users time on building it.

**Comment by apls777** [comment]
Just released the version 1.1.8. The timeout was increased to 30 minutes.
