### ISSUE TITLE
EBS volum mount/unmount instead of snapshot

### ISSUE THREAD

**Issue by jagin** [apls777/spotty#25]
Hi again :)

I'm testing **Spotty** intensively often running `spot start` and `spot stop`. My volume data is about 50GB and it takes ages for taking a snapshot of it and than recreating the volume. I was wonder if it is possible to just mount/unmount EBS volume during start/stop instance and create a snapshot by `spotty stop --snapshot` command.

Regards

Jarek

**Comment by apls777** [comment]
Yes, you can change deletion policy for that volume. See "volumes" -> "deletionPolicy" [here](https://github.com/apls777/spotty/wiki/Configuration-File#instance-section).
**Note**: at the moment deletion policies applied during the stack creation. It means that if you change a deletion policy in the configuration file after your instance is started, it will not change the behaviour on the `spotty stop`. In the Spotty v1.2 this behaviour will be changed, deletion policies will be applied directly from the config.

**Comment by jagin** [comment]
Spotty is the best. I missed that point of the documentation. Thank you!
