### ISSUE TITLE
Error while creating IAM role for instance

### ISSUE THREAD

**Issue by ZohaibAhmed** [apls777/spotty#31]
Hi,

Coming back to this project after a while. I'm following the tutorial here: https://towardsdatascience.com/how-to-train-deep-learning-models-on-aws-spot-instances-using-spotty-8d9e0543d365

I get an error while it tries to create AMI.

```
Tacotron-2 at master ✖ spotty create-ami
Waiting for the AMI to be created...
  - creating IAM role for the instance...
Error:
------
Stack "spotty-nvidia-docker-ami-qgogoanj" was not created.
See CloudFormation and CloudWatch logs for details.
```

**Comment by apls777** [comment]
Hi @ZohaibAhmed,

Can you, please, go to your AWS account -> CloudFormation service, find there the AMI stack (it has name "spotty-nvidia-docker-ami-xxxxxxxx"), open it and check what is the error message in the "Events" tab.

**Comment by ZohaibAhmed** [comment]
@apls777 It shows that there are no stacks (failed, deleted, or otherwise)? Seems like spotty didn't get around to creating the stack at all?

**Comment by apls777** [comment]
@ZohaibAhmed make sure you are looking stack in the right region, it should be there

**Comment by ZohaibAhmed** [comment]
@apls777 Got it, was looking at the default region, not the one in the spotty config. Here's the error:

```
CREATE_FAILED | AWS::Lambda::Function | SetLogsRetentionFunction | The runtime parameter of nodejs4.3 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: bb4a9a9b-3ab9-11e9-b03f-151ba91a4517)
-- | -- | -- | --
```

**Comment by apls777** [comment]
@ZohaibAhmed it seems you are using old version of the tool. Use the `pip install -U spotty` command to update it.

**Comment by ZohaibAhmed** [comment]
Thanks, also seemed like I need to request an increase for the particular instance I was allocating.

**Comment by apls777** [comment]
@ZohaibAhmed What do you mean by "request an increase"?

**Comment by ZohaibAhmed** [comment]
I had a limit on the particular type of instance I wanted to use (by default it was 0). Had to open a case with Amazon to allocate more (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html)

**Comment by ZohaibAhmed** [comment]
@apls777 Don't want to open another issue on this repo for this, but all of the sudden, I get this error when I create-ami using spotty:

```
ract_config.py:46: YAMLLoadWarning:
  *** Calling yaml.load() without Loader=... is deprecated.
  *** The default Loader is unsafe.
  *** Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Waiting for the AMI to be created...
  - creating IAM role for the instance...
  - launching the instance...
  - installing NVIDIA Docker...
Error:
------
Stack "spotty-nvidia-docker-ami-hc4o3367" was not created.
See CloudFormation and CloudWatch logs for details.
```

![image](https://user-images.githubusercontent.com/660224/53617845-db7fc980-3b9d-11e9-9ac3-d87be3882cd0.png)

Any ideas?

**Comment by apls777** [comment]
@ZohaibAhmed Apparently, new version of Docker CE was released, but NVIDIA Docker depends on the previous version. Here is a new [issue](https://github.com/apls777/spotty/issues/32). I'll fix this problem today.
