### ISSUE TITLE
boto3 CreateBucket fails if region is "us-east-1"

### ISSUE THREAD

**Issue by vadimkantorov** [apls777/spotty#43]
If `us-east-1` is used as region, `spotty start` fails with:
```
Error:
------
An error occurred (InvalidLocationConstraint) when calling the CreateBucket operation: The specified location-constraint is not valid
``` 

The solution is to fix https://github.com/apls777/spotty/blob/master/spotty/providers/aws/deployment/project_resources/bucket.py#L31-L32 as
```python
if self._region != 'us-east-1':
  self._s3.create_bucket(ACL='private', Bucket=bucket_name,
                                       CreateBucketConfiguration={'LocationConstraint': self._region})
else:
  self._s3.create_bucket(ACL='private', Bucket=bucket_name)
```

The boto3 issue is decribed in https://github.com/boto/boto3/issues/125

Also, thanks for the great project ^^

**Comment by apls777** [comment]
Thank you for this bug report! I'll fix it with the next release.

**Comment by apls777** [comment]
Fix released.
