### ISSUE TITLE
[feature request] Parameter to select EBS volume type

### ISSUE THREAD

**Issue by vadimkantorov** [apls777/spotty#45]
Currently EBS volumes are created using `standard` type which corresponds to ["previous-generation HDD suitable for infrequently accessed storage"](https://docs.aws.amazon.com/en_us/AWSEC2/latest/UserGuide/EBSVolumeTypes.html). I can convert the volume type in the AWS console, but it would be nice to specify the volume type at its creation.

Also, the EBS volume type `standard` does not support volumes larger than 1 Tb.

The fix would be adding `'VolumeType' : 'gp2'` (or a configurable volume type) at https://github.com/apls777/spotty/blob/master/spotty/providers/aws/deployment/cf_templates/instance_template.py#L114

**Comment by apls777** [comment]
Thank you, Vadim! I'll fix it this week.

**Comment by apls777** [comment]
Now it's the "gp2" volume type by default and there is the "type" parameter in the volume configuration to be able to change it.

The "io1" volume type is not supported at the moment, it requires an additional parameter: "iops". If you need specifically this volume type, feel free to open another issue.
