### ISSUE TITLE
Argument parsing doesn't accept parameter settings before SCRIPT_NAME

### ISSUE THREAD

**Issue by vadimkantorov** [apls777/spotty#49]
Despite the usage info, setting `-p` before `SCRIPT_NAME` doesn't work. It would be great if usage documentation was harmonized with actual behavior.
```
vadimkantorov@5CD8223LBY:~/convasr/scripts$ spotty run -p TAG=master train
usage: spotty run [-h] [-d] [-c CONFIG] [-s SESSION_NAME] [-S] [-l] [-r]
                  [-p [PARAMETER=VALUE [PARAMETER=VALUE ...]]]
                  [INSTANCE_NAME] SCRIPT_NAME
spotty run: error: the following arguments are required: SCRIPT_NAME

vadimkantorov@5CD8223LBY:~/convasr/scripts$ spotty run train -p TAG=master # works
```

**Comment by apls777** [comment]
Thanks for pointing out. It's an argparse bug, but following [this](https://stackoverflow.com/questions/26985650/argparse-do-not-catch-positional-arguments-with-nargs/26986546#26986546) StackOverflow question, I think the best option is to use the `-p` flag before each parameter. I'll add this fix with the next release.

**Comment by apls777** [comment]
Fix released.
