### ISSUE TITLE
Change Docker version to 19.03.2

### ISSUE THREAD

**Issue by jagin** [apls777/spotty#56]
In my Dockerfile I have:
`COPY --chown=$APP_USER:$APP_GID`
but `$APP_USER` is not recognized because of the error https://github.com/moby/moby/issues/35018
It is fixed in version 19.03.2 (it is not working with 19.03.0 even the say so in the issue comment :) ).

**Comment by apls777** [comment]
@jagin Change the Docker version for a custom AMI to 19.03.5. Also, if you didn't create your custom AMI with the `spotty aws create-ami` command, Spotty was using the latest "Deep Learning Base AMI". But, unfortunately, AWS stopped maintaining the "Base" version of their DL AMI, so the Docker version in the latest version was quite old. Now I fixed it to use the latest version of the standard "Deep Learning AMI", it should have one of the latest Docker versions.
