### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by vezzick** [apls777/spotty#57]
Can this be run on windows?
When I do
`spotty start`
it asks me to open a file, if I open it with notepad it shows some python code. If I open it with python it quickly disappears.
Following the instructions as from the medium article

**Comment by apls777** [comment]
It was working for me on a Windows machine. I used it with Git Bash (MinGW). Try it, if you're using the standard Windows terminal at the moment.

**Comment by vezzick** [comment]
Thanks, using git bash solved this problem, but now running into some issues with 
```
[dry-run] Error:
[dry-run] ------
[dry-run] [WinError 2] The system cannot find the file specified
```

I dug into this a bit, it seems like it is because the aws command is using backslashes in the directory name, which is treated as an escape in git bash.
Either it should put quotes around the project directory or it should escape properly.

**Comment by apls777** [comment]
Are you using backslashes for the paths in the `spotty.yaml` file? Try to use Unix-style paths.

**Comment by apls777** [comment]
Closing the issue. If you still have problems, feel free to reopen it.
