### ISSUE TITLE
How to increase Image size

### ISSUE THREAD

**Issue by Tarang** [apls777/spotty#60]
I have an instance thats got files in it that are quite big. In order to prepare the docker image the machine needs more space. The docker workspace has plenty of space, but in order to create the docker image to begin with, the Spotty AMI Image needs to be a bit bigger.

Is there a way to increase its size?

**Comment by apls777** [comment]
Yes, you can specify any size for the root EBS volume using the `rootVolumeSize` parameter in the instance configuration.
